- name: configure nginx
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: remove file
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent