- name: configure mysql
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql-server
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
    
  - name: enable and start mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: install pymysql
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - PyMysql
    - cryptography

  - name: set root password
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1